# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19       

    # Install necessary system dependencies for GLFW and X11
    - name: Install system dependencies
      run: sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev
        
    - uses: evantorrie/mott-the-tidier@v1-beta
      with:
        gomods: |
          **/go.mod
          -tools/go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
